name: Daily PTT Spider

on:
  #schedule:
    #f- cron: '0 0 * * *'   # 每天 00:00 UTC（台灣時間早上 8:00）格式：分 時 日 月 星期
  workflow_dispatch:       # 允許手動觸發

jobs:
  run-spider:
    runs-on: ubuntu-latest

    steps:  
    # 把你這個 repo 的內容 clone 下來，才能執行 .py 檔
    - name: Checkout code    
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # 指定 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run PTT Spider
      run: python static.py

    - name: Upload result (CSV)
      uses: actions/upload-artifact@v4        # 官方提供的上傳工具
      with:
        name: ptt-result
        path: static.csv
